import sys
from typing import List, Optional, Tuple, ClassVar
from .trie import Trie

class BaseCollator:
    CJK_IDEOGRAPHS_8_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_10_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_A: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_B: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_C: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_D: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_E: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_F: ClassVar[bool] = ...
    table: Trie
    implicit_weights: List[List[int]] = ...
    def __init__(self, filename: Optional[str] = ...) -> None: ...
    def load(self, filename: str) -> None: ...
    def collation_elements(
        self,
        normalized_string: str
    ) -> List[List[int]]: ...
    def sort_key_from_collation_elements(
        self,
        collation_elements: List[List[int]]
    ) -> Tuple[int, ...]: ...
    def sort_key(self, string: str) -> Tuple[int, ...]: ...
    def implicit_weight(self, cp: int) -> List[List[int]]: ...
    def build_lookup_key(self, text: str) -> List[int]: ...

class Collator_6_3_0(BaseCollator):
    UCA_VERSION: ClassVar[str] = ...

class Collator_8_0_0(BaseCollator):
    UCA_VERSION: ClassVar[str] = ...
    CJK_IDEOGRAPHS_8_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_E: ClassVar[bool] = ...

class Collator_9_0_0(BaseCollator):
    UCA_VERSION: ClassVar[str] = ...
    CJK_IDEOGRAPHS_8_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_E: ClassVar[bool] = ...

class Collator_10_0_0(BaseCollator):
    UCA_VERSION: ClassVar[str] = ...
    CJK_IDEOGRAPHS_8_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_10_0_0: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_E: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_F: ClassVar[bool] = ...

class Collator_5_2_0(BaseCollator):
    UCA_VERSION: ClassVar[str] = ...
    CJK_IDEOGRAPHS_EXT_C: ClassVar[bool] = ...
    CJK_IDEOGRAPHS_EXT_D: ClassVar[bool] = ...
    non_char_code_points: ClassVar[List[int]] = ...
    def build_lookup_key(self, text: str) -> List[int]: ...

if sys.version_info < (3,):
    Collator = Collator_5_2_0
elif sys.version_info[:2] == (3, 5):
    Collator = Collator_8_0_0
elif sys.version_info[:2] >= (3, 6):
    Collator = Collator_9_0_0
else:
    Collator = Collator_6_3_0
