from typing import Iterable, List, Optional

def hexstrings2int(hexstrings: Iterable[str]) -> List[int]: ...
def int2hexstrings(number_list: Iterable[int]) -> List[str]: ...
def format_collation_elements(
    collation_elements: Optional[List[List[int]]]
) -> Optional[str]: ...
def format_sort_key(sort_key: List[int]) -> str: ...
